project_id = "uyoemkwlccljqyigmcch"

[functions.create-payment]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.connect-create-account]
verify_jwt = true

[functions.connect-check-status]
verify_jwt = true

[functions.stripe-pk]
verify_jwt = false

[functions.doordash-quote]
verify_jwt = true

[functions.doordash-create]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.doordash-webhook]
verify_jwt = false

[functions.geocode]
verify_jwt = true

[functions.chef-analytics]
verify_jwt = true
